### ISSUE TITLE
Incorrect version in master pom

### ISSUE THREAD

**Issue by ppllaxxa** [ITDSystems/alvex-2.x#10]
Hellow! After update to Alvex 2014.05, you forget change 
<documents_registers.version>1.25</documents_registers.version>
to
<documents_registers.version>1.26</documents_registers.version>
in master-pom

**Comment by avasyukov** [comment]
Could you, please, recheck it?

master-pom at http://maven.itdhq.com/public/maven/repository/com/alvexcore/master-pom/1.0/master-pom-1.0.pom contains correct version

**Comment by ppllaxxa** [comment]
Thank you! locally master-pos wasn't updated.
