### ISSUE TITLE
Source code version

### ISSUE THREAD

**Issue by giangkt** [ITDSystems/alvex-2.x#2]
Hi team,

The current source code is still in version 1.3 not 1.3.01. When I compiled the custom-workflows code, it seemed not to be compatible with Alfresco 4.2.a.

Please commit your code.

Thanks for this great job,
Giang.

**Comment by avasyukov** [comment]
Hello Giang,

Sorry for that. We commited everything a week and half ago at the moment of 1.3.0.1 GA. However, it looks like sync to Github failed. It is fixed now. Please, check.

Alexey
