### ISSUE TITLE
PackageItems dont shown on start workflow page.

### ISSUE THREAD

**Issue by ppllaxxa** [ITDSystems/alvex-2.x#3]
When I select the type of workflow, and then select the attachment, nothing happens. Attachment dont shown in table. It detected only in standart workflows.

**Comment by avasyukov** [comment]
Hello ppllaxxa.

Sorry, but I didn't get it. Could you please describe steps to reproduce the problem?

Alexey

**Comment by ppllaxxa** [comment]
Alfresco 4.0.e
Alvex 1.3
When I tried start workflow and select attachment for this workflow in
table of content did not shown this attachment. This reproduce only with
standart workflow like Adhoc for example. But your uploader controller
works fine.

**Comment by avasyukov** [comment]
It should be solved by 7b0610eb61c05a24b17f00802a5232d3578c3cee

Sorry for the delay with the resolution. It was the issue with Share modules we use to deploy extensions. We will report it to Alfresco asap and workaround is available now.
