### ISSUE TITLE
Custom extension development

### ISSUE THREAD

**Issue by giangkt** [ITDSystems/alvex-2.x#5]
Hi there!

Your framework is so cute and I'd like to develop some custom extensions (module, dashlet,..) based on this. Any glue to me?

Thanks for your great works.

Giang.

**Comment by avasyukov** [comment]
Any ideas what do you need from our side? :-) I'd like to provide links, references, examples or whatever - but I do not understand what kind of information you need now.

Could you describe in brief how we can help? Or - alternatively - could you share the ideas what you are going to develop?

**Comment by aviriel** [comment]
close as outdated
