### ISSUE TITLE
Error with the Github code compilation (4.2.c)

### ISSUE THREAD

**Issue by giangkt** [ITDSystems/alvex-2.x#6]
Hi there!

Using the compilation from github with 4.2.c, there is an error: Caused by: org.alfresco.service.namespace.NamespaceException: Namespace prefix itdrwf is not mapped to a namespace URI when I open My Tasks function.

Giang.

**Comment by ksergeev** [comment]
Hello. This issue is caused by Alvex internal API update. It will be resolved in few days - as soon as I complete API changes it will be resolved automatically. I'll post here when it will be done.

**Comment by giangkt** [comment]
That's great! Thanks Sergeev.
