### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by ghost** [ITDSystems/alvex-2.x#8]
Hello!, Please help me. when i build with command: ant build-all is errors:
    [javac] Compiling 5 source files to E:\demo\alvex-master\core\custom-workflo
ws\build\repo-jar
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:37: error: cannot find symbol
    [javac] public class CustomWorkflowsExtension extends RepositoryExtension {
    [javac]                                               ^
    [javac]   symbol: class RepositoryExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:43: error: cannot find symbol
    [javac]             id = "custom-workflows";
    [javac]             ^
    [javac]   symbol:   variable id
    [javac]   location: class CustomWorkflowsExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:44: error: cannot find symbol
    [javac]             fileListPath = "alvex-custom-workflows-file-list.txt";
    [javac]             ^
    [javac]   symbol:   variable fileListPath
    [javac]   location: class CustomWorkflowsExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:45: error: cannot find symbol
    [javac]             extInfoPath = "alvex-custom-workflows.properties";
    [javac]             ^
    [javac]   symbol:   variable extInfoPath
    [javac]   location: class CustomWorkflowsExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:50: error: cannot find symbol
    [javac]             super.init(failIfInitialized);
    [javac]             ^
    [javac]   symbol:   variable super
    [javac]   location: class CustomWorkflowsExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:51: error: cannot find symbol
    [javac]             AuthorityService as = serviceRegistry.getAuthorityServic
e();
    [javac]                                   ^
    [javac]   symbol:   variable serviceRegistry
    [javac]   location: class CustomWorkflowsExtension
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:48: error: method does not override or
implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] E:\demo\alvex-master\core\custom-workflows\source\java\repo\com\alve
xcore\repo\CustomWorkflowsExtension.java:62: error: method does not override or
implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] 8 errors

**Comment by fufler** [comment]
I guess you need to configure build properties (see [this](https://github.com/ITDSystems/alvex/issues/1#issuecomment-9155504)).
